language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install scipy
  #- pip install astropy
  - pip install astrobase
script:
  - cd test
  - python test_lc_class_initialization.py
  - python test_data_processing_ls_shorterfortravis.py
  - python test_data_processing_pdm_shorterfortravis.py
  - python test_data_processing_bls.py
  - python test_snr_calculation.py
  - python test_simple_deblend_functions.py
  - python test_data_processing_generalstuff.py
branches:
  only:
    - master
