language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install scipy
script:
  - cd test
  - python test_lc_class_initialization.py
  - python test_data_processing.py
branches:
  only:
    - master
